<<<<<<< HEAD
=======
/* GET HELP */
export const GET_HELP = "GET_HELP";
export const GET_HELP_SUCCESS = "GET_HELP_SUCCESS";
export const GET_HELP_FAIL = "GET_HELP_FAIL";

/* ADD HELP */
export const ADD_NEW_HELP = "ADD_NEW_HELP";
export const ADD_NEW_HELP_SUCCESS = "ADD_NEW_HELP_SUCCESS";
export const ADD_NEW_HELP_FAIL = "ADD_NEW_HELP_FAIL";

/* EDIT HELP */
export const UPDATE_HELP = "UPDATE_HELP";
export const UPDATE_HELP_SUCCESS = "UPDATE_HELP_SUCCESS";
export const UPDATE_HELP_FAIL = "UPDATE_HELP_FAIL";

/* DELETE HELP */
export const DELETE_HELP = "DELETE_HELP";
export const DELETE_HELP_SUCCESS = "DELETE_HELP_SUCCESS";
export const DELETE_HELP_FAIL = "DELETE_HELP_FAIL";

>>>>>>> f8a4dd6030653996833187bae2a7f6b6a31dae75
/* ADD CONTACT */
export const ADD_NEW_CONTACT = "ADD_NEW_CONTACT";
export const ADD_NEW_CONTACT_SUCCESS = "ADD_NEW_CONTACT_SUCCESS";
export const ADD_NEW_CONTACT_FAIL = "ADD_NEW_CONTACT_FAIL";
<<<<<<< HEAD

export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAIL = "UPLOAD_IMAGE_FAIL";

export const CLEAR_IMAGE = "CLEAR_IMAGE";

export const CLEAR_ALL_IMAGE = "CLEAR_ALL_IMAGE";

export const GET_ALL_CONTACT = "GET_ALL_CONTACT";
export const GET_ALL_CONTACT_SUCCESS = "GET_ALL_CONTACT_SUCCESS";
export const GET_ALL_CONTACT_FAIL = "GET_ALL_CONTACT_FAIL";

export const GET_CONTACT_DETAILS = "GET_CONTACT_DETAILS";
export const GET_CONTACT_DETAILS_SUCCESS = "GET_CONTACT_DETAILS_SUCCESS";
export const GET_CONTACT_DETAILS_FAIL = "GET_CONTACT_DETAILS_FAIL";
=======
>>>>>>> f8a4dd6030653996833187bae2a7f6b6a31dae75
