/* GET HELP */
export const GET_HELP = "GET_HELP";
export const GET_HELP_SUCCESS = "GET_HELP_SUCCESS";
export const GET_HELP_FAIL = "GET_HELP_FAIL";

/* ADD HELP */
export const ADD_NEW_HELP = "ADD_NEW_HELP";
export const ADD_NEW_HELP_SUCCESS = "ADD_NEW_HELP_SUCCESS";
export const ADD_NEW_HELP_FAIL = "ADD_NEW_HELP_FAIL";

/* EDIT HELP */
export const UPDATE_HELP = "UPDATE_HELP";
export const UPDATE_HELP_SUCCESS = "UPDATE_HELP_SUCCESS";
export const UPDATE_HELP_FAIL = "UPDATE_HELP_FAIL";

/* DELETE HELP */
export const DELETE_HELP = "DELETE_HELP";
export const DELETE_HELP_SUCCESS = "DELETE_HELP_SUCCESS";
export const DELETE_HELP_FAIL = "DELETE_HELP_FAIL";

/* ADD CONTACT */
export const ADD_NEW_CONTACT = "ADD_NEW_CONTACT";
export const ADD_NEW_CONTACT_SUCCESS = "ADD_NEW_CONTACT_SUCCESS";
export const ADD_NEW_CONTACT_FAIL = "ADD_NEW_CONTACT_FAIL";
