


/* GET ORDER_MANAGEMENT */
export const GET_ORDER_MANAGEMENT = "GET_ORDER_MANAGEMENT"
export const GET_ORDER_MANAGEMENT_SUCCESS = "GET_ORDER_MANAGEMENT_SUCCESS"
export const GET_ORDER_MANAGEMENT_FAIL = "GET_ORDER_MANAGEMENT_FAIL"

/* ADD ORDER_MANAGEMENT */
export const ADD_NEW_ORDER_MANAGEMENT = "ADD_NEW_ORDER_MANAGEMENT"
export const ADD_NEW_ORDER_MANAGEMENT_SUCCESS = "ADD_NEW_ORDER_MANAGEMENT_SUCCESS"
export const ADD_NEW_ORDER_MANAGEMENT_FAIL = "ADD_NEW_ORDER_MANAGEMENT_FAIL"

/* EDIT ORDER_MANAGEMENT */
export const UPDATE_ORDER_MANAGEMENT = "UPDATE_ORDER_MANAGEMENT"
export const UPDATE_ORDER_MANAGEMENT_SUCCESS = "UPDATE_ORDER_MANAGEMENT_SUCCESS"
export const UPDATE_ORDER_MANAGEMENT_FAIL = "UPDATE_ORDER_MANAGEMENT_FAIL"

/* DELETE ORDER_MANAGEMENT */
export const DELETE_ORDER_MANAGEMENT = "DELETE_ORDER_MANAGEMENT"
export const DELETE_ORDER_MANAGEMENT_SUCCESS = "DELETE_ORDER_MANAGEMENT_SUCCESS"
export const DELETE_ORDER_MANAGEMENT_FAIL = "DELETE_ORDER_MANAGEMENT_FAIL"

/* GET ORDER_DETAILS */
export const GET_ORDER_DETAILS = "GET_ORDER_DETAILS"
export const GET_ORDER_DETAILS_SUCCESS = "GET_ORDER_DETAILS_SUCCESS"
export const GET_ORDER_DETAILS_FAIL = "GET_ORDER_DETAILS_FAIL"
